config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  post 'update', to: 'balances#create'

  post 'report_bill_transaction', to: 'bill_logs#create'
  post 'report_enrich_transaction', to: 'enrichment_logs#create'
  post 'report_necessities_transaction', to: 'necessity_logs#create'
  post 'report_whims_transaction', to: 'whim_logs#create'
  post 'report_invest_transaction', to: 'investment_logs#create'
  post 'report_cap_transaction', to: 'philanthropy_logs#create'
  post 'report_savings_transaction', to: 'security_logs#create'

  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/curate', to: 'curator_sessions#new'
  post '/curate', to: 'curator_sessions#create'
  delete '/close', to: 'curator_sessions#destroy'

  post '/fa', to: 'financial_assistants#create'

  resources :users do
  	resources :necessities do
  		resources :necessity_logs 
  	end
  	resources :bills do 
  		resources :bill_logs
  	end
  	resources :enrichments do
  		resources :enrichment_logs
  	end
  	resources :investments do 
  		resources :investment_logs
  	end
  	resources :philanthropies do 
  		resources :philanthropy_logs
  	end
  	resources :securities do
  		resources :security_logs
  	end
  	resources :whims do 
  		resources :whim_logs
  	end

    resources :balances
  end

  resources :financial_assistants
  resources :curators




  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  has_many :bill_logs
  validates :available_balance, presence: true
end

app/models/bill_log.rb
class BillLog < ApplicationRecord
  belongs_to :bill
  validates :amount_spent, presence: true
  validates :type_of_spending, presence: true

end

app/models/curator.rb
class Curator < ApplicationRecord
	before_save {username.downcase!}
	VALID_USERNAME = /@[a-z\d\-]/
	validates :username, presence: true, length: {maximum: 75}, format: {with: VALID_USERNAME}, uniqueness: true

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns the hash digest of the given string.
  def Curator.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/models/enrichment.rb
class Enrichment < ApplicationRecord
  belongs_to :user
  has_many :enrichment_logs
  validates :available_balance, presence: true
end

app/models/enrichment_log.rb
class EnrichmentLog < ApplicationRecord
  belongs_to :enrichment
    validates :amount_spent, presence: true
  validates :type_of_spending, presence: true
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  has_many :investment_logs
  validates :available_balance, presence: true
end

app/models/investment_log.rb
class InvestmentLog < ApplicationRecord
  belongs_to :investment
    validates :amount_spent, presence: true
  validates :type_of_spending, presence: true
end

app/models/necessity.rb
class Necessity < ApplicationRecord
  belongs_to :user
  has_many :necessity_logs
  validates :available_balance, presence: true
end

app/models/necessity_log.rb
class NecessityLog < ApplicationRecord
  belongs_to :necessity
    validates :amount_spent, presence: true
  validates :type_of_spending, presence: true
end

app/models/philanthropy.rb
class Philanthropy < ApplicationRecord
  belongs_to :user
  has_many :philanthropy_logs
  validates :available_balance, presence: true
end

app/models/security.rb
class Security < ApplicationRecord
  belongs_to :user
  has_many :security_logs
  validates :available_balance, presence: true
end

app/models/security_log.rb
class SecurityLog < ApplicationRecord
  belongs_to :security
    validates :amount_spent, presence: true
  validates :type_of_spending, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bill, dependent: :destroy
  has_many :enrichment, dependent: :destroy
  has_many :necessity, dependent: :destroy
  has_many :philanthropy, dependent: :destroy
  has_many :security, dependent: :destroy
  has_many :whim, dependent: :destroy
  has_many :balances, dependent: :destroy
  
	attr_accessor :remember_token, :activation_token,  :reset_token
	before_save :downcase_email
  before_create :create_activation_digest
	validates :firstname, presence: true, length: {maximum: 50}
	validates :lastname, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end

  	def User.new_token
    	SecureRandom.urlsafe_base64
  	end

  	def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
  	end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  	def forget
    	update_attribute(:remember_digest, nil)
  	end


    # Activates an account.
  def activate
    update_columns(activated: FILL_IN, activated_at: FILL_IN)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

   # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  FILL_IN, reset_sent_at: FILL_IN)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

   def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

    private
    def downcase_email
      self.email = email.downcase
    end


    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/models/whim.rb
class Whim < ApplicationRecord
  belongs_to :user
  has_many :whim_logs
  validates :available_balance, presence: true
end

app/models/whim_log.rb
class WhimLog < ApplicationRecord
  belongs_to :whim
  validates :amount_spent, presence: true
  validates :type_of_spending, presence: true
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/curators_helper.rb
module CuratorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/whims_helper.rb
module WhimsHelper
end

app/views/bills/_bill_trust.html.erb
<h1 class="trust_header"> Bills Trust</h1>
<div class="desc">
		<p class="trust_des"> Description </p>
	<p style="color:#0D6F7A ;"> Funds services rendered by an external source.<br>
	Recurring or onetime amounts paid to someelse for a service is a bill.<br>
	 Examples include phone, internet, electric, insurance, vet, tuition,<br>
	 car service, nanny, house cleaning, landscaping, dog walker, dog nanny.<br>
	  </p>
</div>	
<% @my_bills = Bill.where(user_id: current_user.id) %>
<% if @my_bills.empty? %>
<div class="c_b">
<h3 class="curr_bal">  Current Funds Available for Bill </h3>
<h1 class="curr_b" > Please Update Your Balance to Add Funds </h1>
</div>

<div class="past_b">
<h4 class="past_bal"> Past Balances </h4>

</div>


<% else %>
<div class="c_b">
<h3 class="curr_bal">  Current Funds Available for Bill </h3>
<h1 class="curr_b" > $ <%= @my_bills.last.available_balance %> </h1>
</div>


<div class="past_b">
<h4 class="past_bal"> Past Balances </h4>
<div class="past_holder">
<% @my_bills.each do |bill| %>
	<div class="past_balances">
		<p class="p_b"><%= bill.created_at.strftime("%b %d, %Y") %></p>
		<p class="p_b p_b_amt">$ <%= bill.available_balance %></p>
	</div>
<% end %>
</div>
</div>
<% end %>

app/views/bills/_update_bills_trust.html.erb
<h4 class="form-header"> REPORT TRANSACTION </h4>
<%= form_for(:bill_log, url: report_bill_transaction_path) do |f| %>

      <label>
		<%= f.text_field :amount_spent,:required => true%> 
		<div class="label-text" > Amount Spent </div>
	  </label>

	  <label>
		<%= f.select :type_of_spending, ['Car Insurance', 'Home Insurance', 'Vet Insurance',
			'Medical', 'Home Repair', 'Landscaping', 'Credit Card', 'Mortgage', 'Loan', 'Gym/Studio Membership', 'Phone', 'Prime', 'Grocery Delivery Service', 'Babysitting', 'Exercise Class', 'iTunes', 'YouTube Membership', 'Tuition', 'HOA', 'Taxes', 'Internet', 'Spa', 'Hair Salon/Barber', 'Other Recurring Membership', 'Other Onetime Service'
		 ], :class => "select_spending"  %>
	  </label>

	   <%= f.submit "Save" %>


<% end %>